title:              Clean Blog
email:              loop1397@naver.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            ""
url:                "http://omnomnomnom.mooo.com/"

# Social Profiles
twitter_username:   Pinbol
github_username:    Pinbol
facebook_username:  Pinbol
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
